### ISSUE TITLE
Error on version >= 4.8.0

### ISSUE THREAD

**Issue by rpc1910** [legend80s/git-commit-msg-linter#35]
After version 4.8.0, when I install the dependency and try do a commit, this error is returned

![image](https://user-images.githubusercontent.com/2295384/222482221-405a487f-bf35-4772-b905-fc22e7d0af23.png)

In this test, I've created a simple repository with git and just add git-commit-msg-linter dependency.

**Comment by legend80s** [comment]
try 4.8.1

**Comment by rpc1910** [comment]
I've tested both versions and I had the same error

**Comment by legend80s** [comment]
ok i will look into this cc @zanminkian

**Comment by legend80s** [comment]
can you create a GitHub repo for reproduction

**Comment by legend80s** [comment]
It reproduced. You can use 4.7 for now and I will fix it as soon as possible.

**Comment by legend80s** [comment]
Fix it git-commit-msg-linter@4.8.2

**Comment by zanminkian** [comment]
I can't reproduce it. Could you provide a minimal reproducible example. @legend80s

**Comment by legend80s** [comment]
1. mkdir an empty directory
2. cd it
3. npm init
4. npm install git-commit-msg-linter@4.8.1
5. git commit anything

**Comment by rpc1910** [comment]
The version 4.8.2 is working!! Thank you!!

**Comment by zanminkian** [comment]
v4.8.1 works for me on ubuntu. I still can't reproduce. What's your system? @legend80s

**Comment by rpc1910** [comment]
@zanminkian , my OS is macOS Monterrey 12.5.1

**Comment by legend80s** [comment]
yes mac os will reproduce it @zanminkian
