### ISSUE TITLE
error: cannot spawn .git/hooks/commit-msg: No such file or directory

### ISSUE THREAD

**Issue by lbertoncello** [legend80s/git-commit-msg-linter#38]
I'm getting the following error when trying to commit just after installing `git-commit-msg-linter` in my project: 

`error: cannot spawn .git/hooks/commit-msg: No such file or directory`

The project is just Vue.js boilerplate created with Vite. You can check it [here](https://github.com/lbertoncello/my-games-list/releases/tag/0.0.1).

My `commit-msg` file using the current version of `git-commit-msg-linter` is the following:

```
# git-commit-msg-linter@4.9.2 3/29/2023, 3:54:43 PM
# id=commit-msg-linter - THE id COMMENT SHOULD NOT BE DELETED OR MODIFIED!
# It's used to check whether this commit-msg hook file is created by us,
# if it is then we can remove it confidently on uninstallation.

cat E:\Dev\Treinamentos\my-games-list\.yarn\unplugged\git-commit-msg-linter-npm-4.9.2-060e731a8e\node_modules\git-commit-msg-linter\commit-msg-linter.js | node --input-type=commonjs
```

I managed to fix this error rolling `git-commit-msg-linter` back to the version I was using before on my projects (version 4.1.2) which has the following `commit-msg` file:

```
#!/bin/bash
#
# Solve the problem of [Wishlist: support for ES6 modules. #14].
# https://github.com/legend80s/commit-msg-linter/issues/14

# This shell script template is from: https://google.github.io/styleguide/shellguide.html

# $0: .git/hooks/commit-msg, $1: .git/COMMIT_EDITMSG, $2: , $3:
# node '.git/hooks/commit-msg-linter.js' $1

# id=commit-msg-linter - The comment SHOULD NOT BE DELETED.

# https://nodejs.org/api/packages.html#--input-type-flag
cat .git/hooks/commit-msg-linter.js | node --input-type=commonjs

```

OS: Windows 11
Node: v18.15.0
Yarn: 3.5.0 (I have enabled PnP)

**Comment by alwspiderc** [comment]
this is happening to me too. I installed version 4.5.0 and it's working.
Command: npm install git-commit-msg-linter@4.5.0 --save-dev

**Comment by legend80s** [comment]
> `error: cannot spawn .git/hooks/commit-msg: No such file or directory`

but `.git/hooks/commit-msg` exits according to you comment 🤔.

@lbertoncello

**Comment by lbertoncello** [comment]
> > `error: cannot spawn .git/hooks/commit-msg: No such file or directory`
> 
> but `.git/hooks/commit-msg` exits according to you comment 🤔.
> 
> @lbertoncello

Yes, that's exactly the issue. I only managed to fix this after rolling back to a previous version.

**Comment by lbertoncello** [comment]
> `E:\Dev\Treinamentos\my-games-list\.yarn\unplugged\git-commit-msg-linter-npm-4.9.2-060e731a8e\node_modules\git-commit-msg-linter\commit-msg-linter.js` does it exists?

Yes, it does

**Comment by lbertoncello** [comment]
> I will try to fix it as soon as possible

Nice to know! Thank you for your attention!

**Comment by legend80s** [comment]
Mac
- yarn pnp 1.22.19 v16.19.0 ✅
- yarn pnp 3.5.0  v16.19.0 ✅
- yarn pnp 3.5.0  v18.15.0 ✅

Windows

I don't have a Windows computer, If you have @zanminkian would you like to help to debug this issue? Thanks as always.

```
❯ cat .git/hooks/commit-msg
# git-commit-msg-linter@4.9.2 4/1/2023, 11:44:14 AM
# id=commit-msg-linter - THE id COMMENT SHOULD NOT BE DELETED OR MODIFIED!
# It's used to check whether this commit-msg hook file is created by us,
# if it is then we can remove it confidently on uninstallation.

cat /Users/legend80s/workspace/legend80s/commit-msg-linter-test-pnp-yarn/.yarn/unplugged/git-commit-msg-linter-npm-4.9.2-060e731a8e/node_modules/git-commit-msg-linter/commit-msg-linter.js | node --input-type=commonjs
```

**Comment by zanminkian** [comment]
@legend80s I'm happy to help, but I use ubuntu and mac only and have no windows neither. I think the reason is that `#!/bin/bash` is missing. I created a PR #39 . I hope it works.

**Comment by legend80s** [comment]
fixed @v4.9.3  @lbertoncello

**Comment by lbertoncello** [comment]
> fixed @v4.9.3 @lbertoncello

@legend80s It has another issue now. It doesn't show any errors anymore but the script it's not being executed. After some debugging, I think I have found out the cause. 

The command being generated on my PC is exactly this one:

```
cat E:\Dev\my-games-list\.yarn\unplugged\git-commit-msg-linter-npm-4.9.3-a78cfc1a97\node_modules\git-commit-msg-linter\commit-msg-linter.js | node --input-type=commonjs
```

Since it will run as a bash script (it has `#!/bin/bash` after all) it should use '/' to represent the path instead of '\\'. I changed it to the following command and now it's working:

```
cat E:/Dev/my-games-list/.yarn/unplugged/git-commit-msg-linter-npm-4.9.3-a78cfc1a97/node_modules/git-commit-msg-linter/commit-msg-linter.js | node --input-type=commonjs
```

That being said, I believe it will work fine on Windows after changing the path slash to the Linux standard.

**Comment by legend80s** [comment]
@lbertoncello Thanks 👍. Can you help to test the version `git-commit-msg-linter@4.9.4`?

**Comment by lbertoncello** [comment]
> @lbertoncello Thanks 👍. Can you help to test the version `git-commit-msg-linter@4.9.4`?

Of course

**Comment by lbertoncello** [comment]
> @lbertoncello Thanks 👍. Can you help to test the version `git-commit-msg-linter@4.9.4`?

@legend80s It's working fine for me now. Thank you!
