### ISSUE TITLE
Support exclamation mark for breaking change commit

### ISSUE THREAD

**Issue by zanminkian** [legend80s/git-commit-msg-linter#41]
`feat(xxx)!: support xxx` and `feat!: support xxx` is now very popular today. Please consider supporting this feature.

It's reasonable. We can easily recognize the breaking change commit.

**Comment by zanminkian** [comment]
Check https://www.conventionalcommits.org/en/v1.0.0/

**Comment by zanminkian** [comment]
It's really necessary for me.

**Comment by legend80s** [comment]
OK we will do it

**Comment by legend80s** [comment]
Published + git-commit-msg-linter@4.11.0 🎉. Thanks for your information! That's very useful to me.
