### ISSUE TITLE
Extract the `commit-msg-linter.js` to a sub-library

### ISSUE THREAD

**Issue by zanminkian** [legend80s/git-commit-msg-linter#42]
I have a all-in-one tool ([@zanminkian/git-hooks](https://github.com/zanminkian/git-hooks)) using this npm package as its dependency to check the commit message. The tool of mine will not install if user don't run `git-hooks install`. But I cannot control it because `git-commit-msg-linter` will install automatically, which means it will write the `.git/hooks/commit-msg` file automatically.

I want the dependency - `git-commit-msg-linter` do not setup postinstall script in its `package.json`. But this is a big breaking change which should not come true. The solution is extracting the `commit-msg-linter.js` to a single npm library, named `commit-msg-linter` (or any other name). `git-commit-msg-linter` uses `commit-msg-linter` as its dependency.

May be we have to change this git repo to a monorepo.

**Comment by legend80s** [comment]
yes very reasonable can you make a pr for it

**Comment by legend80s** [comment]
"git-commit-msg-linter": "^5.0.3" published 🎉!
