### ISSUE TITLE
commit-msg hook doesn't work if bash not installed at `/bin/bash`

### ISSUE THREAD

**Issue by emccorson** [legend80s/git-commit-msg-linter#48]
The `commit-msg` hook assumes that bash is installed at `/bin/bash`, but that is not the case for all systems (including NixOS, which is what I'm running).

It looks like this was broken in #39, which added the shebang:

    #!/bin/bash

I think the correct shebang should be:

    #!/usr/bin/env bash

which is [more portable](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my) and should work on systems where bash is somewhere other than `/bin/bash` (although I couldn't say if this solution works for all supported systems).

**Comment by legend80s** [comment]
Here we stick to the shell conventions to google's.

https://google.github.io/styleguide/shellguide.html#file-header

```
#!/bin/bash
#
# Perform hot backups of Oracle databases.
```

**Comment by legend80s** [comment]
And does it work after change it to `#!/usr/bin/env bash` in the file `.git/hook/commit-msg`?

**Comment by emccorson** [comment]
It works after changing to `#!/usr/bin/env bash`.

From my reading of the Google shell convention, it looks like they require bash as the shell. `#!/usr/bin/env bash` still calls bash, but it locates bash instead of assuming the path `/bin/bash`. So it should work for more systems than just ones where bash is located at `/bin/bash` (NixOS definitely, maybe FreeBSD also?).

**Comment by legend80s** [comment]
Fixed and try `git-commit-msg-linter@5.0.6`.

**Comment by emccorson** [comment]
Thanks! Works for me now :tada:
