### ISSUE TITLE
Doesn't work if the project path has spaces

### ISSUE THREAD

**Issue by victorbfcastro** [legend80s/git-commit-msg-linter#52]
The .git/hooks/commit-msg of my project is at this path: "C:\Workplace\One drive\Example-Project\.git\hooks\commit-msg"

Since there is a space at "\One drive\" in the path, the lib doesn't work correctly because it configures the path to the lib in the commit-msg file without the quotes, like that:

```
#!/usr/bin/env bash
#
# git-commit-msg-linter@5.0.7 03/04/2024, 14:57:24
# id=commit-msg-linter - THE id COMMENT SHOULD NOT BE DELETED OR MODIFIED!
# It's used to check whether this commit-msg hook file is created by us,
# if it is then we can remove it confidently on uninstallation.

cat C:/Workplace/One drive/Example-Project/node_modules/commit-msg-linter/commit-msg-linter.js | node --input-type=commonjs
```

When this should be like (with quotes):
`cat "C:/Workplace/One drive/Example-Project/node_modules/commit-msg-linter/commit-msg-linter.js" | node --input-type=commonjs`

The actual version results in an error message at the cat command. 
(sorry for the bad english since its not my first language)

**Comment by legend80s** [comment]
OK I will try to fix it.
